# Text shown on the index page.
index_title: Kochbuch
index_description: Ansammlung von ausgewählten Rezepten aus dem Internet, etc.

# Whether to show each recipe's image, if available, on the index page. To
# enable, set this option to any non-empty value (other than "false" in recent
# versions of Pandoc). To disable, keep it blank.
show_images_on_index:

# You can change the content language (really only relevant for hyphenation)
# and related textual labels here.
lang: de
strings:
  search_placeholder: Suchen...
  uncategorized_label: Unbekannt
  source_label: Ursprung
  spicy_label: Scharf
  vegan_label: Vegan
  meat_label: Fleisch
  footer_text: Guten Appetit!
  updated_on: Geändert am
  edit: Bearbeiten

# If you maintain your recipes in a GitHub repository, you can specify its URL
# here – if non-empty, an "Edit" link will be shown at the bottom of each recipe
# page, referring you to the corresponding Markdown file on GitHub. If you've
# got some sort of continous integration (like the included GitHub Action) set
# up, this effectively turns your site into a wiki.
github_url: https://github.com/leonhma/nyum

# Remote for deployment – the value of this setting will be passed to rsync as a
# destination, so you probably want it to look like USER@SERVER:PATH. Make sure
# it's correct – the path in particular – since otherwise stuff that shouldn't
# be deleted or overwritten might indeed be deleted or overwritten!
deploy_remote:
